"""
A list of all blocks and their names as of Minecraft 1.20
"""
blocks=[
    ("acacia_button", "Acacia button", "Acacia button"),
    ("acacia_door", "Acacia door", "Acacia door"),
    ("acacia_fence_gate", "Acacia fence gate", "Acacia fence gate"),
    ("acacia_fence", "Acacia fence", "Acacia fence"),
    ("acacia_hanging_sign", "Acacia hanging sign", "Acacia hanging sign"),
    ("acacia_leaves", "Acacia leaves", "Acacia leaves"),
    ("acacia_log", "Acacia log", "Acacia log"),
    ("acacia_planks", "Acacia planks", "Acacia planks"),
    ("acacia_pressure_plate", "Acacia pressure plate", "Acacia pressure plate"),
    ("acacia_sapling", "Acacia sapling", "Acacia sapling"),
    ("acacia_sign", "Acacia sign", "Acacia sign"),
    ("acacia_slab", "Acacia slab", "Acacia slab"),
    ("acacia_stairs", "Acacia stairs", "Acacia stairs"),
    ("acacia_trapdoor", "Acacia trapdoor", "Acacia trapdoor"),
    ("acacia_wall_hanging_sign", "Acacia wall hanging sign", "Acacia wall hanging sign"),
    ("acacia_wall_sign", "Acacia wall sign", "Acacia wall sign"),
    ("acacia_wood", "Acacia wood", "Acacia wood"),
    ("activator_rail", "Activator rail", "Activator rail"),
    ("air", "Air", "Air"),
    ("allium", "Allium", "Allium"),
    ("amethyst_block", "Amethyst block", "Amethyst block"),
    ("amethyst_cluster", "Amethyst cluster", "Amethyst cluster"),
    ("ancient_debris", "Ancient debris", "Ancient debris"),
    ("andesite_slab", "Andesite slab", "Andesite slab"),
    ("andesite_stairs", "Andesite stairs", "Andesite stairs"),
    ("andesite_wall", "Andesite wall", "Andesite wall"),
    ("andesite", "Andesite", "Andesite"),
    ("anvil", "Anvil", "Anvil"),
    ("attached_melon_stem", "Attached melon stem", "Attached melon stem"),
    ("attached_pumpkin_stem", "Attached pumpkin stem", "Attached pumpkin stem"),
    ("azalea_leaves", "Azalea leaves", "Azalea leaves"),
    ("azalea", "Azalea", "Azalea"),
    ("azure_bluet", "Azure bluet", "Azure bluet"),
    ("bamboo_block", "Bamboo block", "Bamboo block"),
    ("bamboo_button", "Bamboo button", "Bamboo button"),
    ("bamboo_door", "Bamboo door", "Bamboo door"),
    ("bamboo_fence_gate", "Bamboo fence gate", "Bamboo fence gate"),
    ("bamboo_fence", "Bamboo fence", "Bamboo fence"),
    ("bamboo_hanging_sign", "Bamboo hanging sign", "Bamboo hanging sign"),
    ("bamboo_mosaic_slab", "Bamboo mosaic slab", "Bamboo mosaic slab"),
    ("bamboo_mosaic_stairs", "Bamboo mosaic stairs", "Bamboo mosaic stairs"),
    ("bamboo_mosaic", "Bamboo mosaic", "Bamboo mosaic"),
    ("bamboo_planks", "Bamboo planks", "Bamboo planks"),
    ("bamboo_pressure_plate", "Bamboo pressure plate", "Bamboo pressure plate"),
    ("bamboo_sapling", "Bamboo sapling", "Bamboo sapling"),
    ("bamboo_sign", "Bamboo sign", "Bamboo sign"),
    ("bamboo_slab", "Bamboo slab", "Bamboo slab"),
    ("bamboo_stairs", "Bamboo stairs", "Bamboo stairs"),
    ("bamboo_trapdoor", "Bamboo trapdoor", "Bamboo trapdoor"),
    ("bamboo_wall_hanging_sign", "Bamboo wall hanging sign", "Bamboo wall hanging sign"),
    ("bamboo_wall_sign", "Bamboo wall sign", "Bamboo wall sign"),
    ("bamboo", "Bamboo", "Bamboo"),
    ("barrel", "Barrel", "Barrel"),
    ("barrier", "Barrier", "Barrier"),
    ("basalt", "Basalt", "Basalt"),
    ("beacon", "Beacon", "Beacon"),
    ("bedrock", "Bedrock", "Bedrock"),
    ("bee_nest", "Bee nest", "Bee nest"),
    ("beehive", "Beehive", "Beehive"),
    ("beetroots", "Beetroots", "Beetroots"),
    ("bell", "Bell", "Bell"),
    ("big_dripleaf_stem", "Big dripleaf stem", "Big dripleaf stem"),
    ("big_dripleaf", "Big dripleaf", "Big dripleaf"),
    ("birch_button", "Birch button", "Birch button"),
    ("birch_door", "Birch door", "Birch door"),
    ("birch_fence_gate", "Birch fence gate", "Birch fence gate"),
    ("birch_fence", "Birch fence", "Birch fence"),
    ("birch_hanging_sign", "Birch hanging sign", "Birch hanging sign"),
    ("birch_leaves", "Birch leaves", "Birch leaves"),
    ("birch_log", "Birch log", "Birch log"),
    ("birch_planks", "Birch planks", "Birch planks"),
    ("birch_pressure_plate", "Birch pressure plate", "Birch pressure plate"),
    ("birch_sapling", "Birch sapling", "Birch sapling"),
    ("birch_sign", "Birch sign", "Birch sign"),
    ("birch_slab", "Birch slab", "Birch slab"),
    ("birch_stairs", "Birch stairs", "Birch stairs"),
    ("birch_trapdoor", "Birch trapdoor", "Birch trapdoor"),
    ("birch_wall_hanging_sign", "Birch wall hanging sign", "Birch wall hanging sign"),
    ("birch_wall_sign", "Birch wall sign", "Birch wall sign"),
    ("birch_wood", "Birch wood", "Birch wood"),
    ("black_banner", "Black banner", "Black banner"),
    ("black_bed", "Black bed", "Black bed"),
    ("black_candle_cake", "Black candle cake", "Black candle cake"),
    ("black_candle", "Black candle", "Black candle"),
    ("black_carpet", "Black carpet", "Black carpet"),
    ("black_concrete_powder", "Black concrete powder", "Black concrete powder"),
    ("black_concrete", "Black concrete", "Black concrete"),
    ("black_glazed_terracotta", "Black glazed terracotta", "Black glazed terracotta"),
    ("black_shulker_box", "Black shulker box", "Black shulker box"),
    ("black_stained_glass_pane", "Black stained glass pane", "Black stained glass pane"),
    ("black_stained_glass", "Black stained glass", "Black stained glass"),
    ("black_terracotta", "Black terracotta", "Black terracotta"),
    ("black_wall_banner", "Black wall banner", "Black wall banner"),
    ("black_wool", "Black wool", "Black wool"),
    ("blackstone_slab", "Blackstone slab", "Blackstone slab"),
    ("blackstone_stairs", "Blackstone stairs", "Blackstone stairs"),
    ("blackstone_wall", "Blackstone wall", "Blackstone wall"),
    ("blackstone", "Blackstone", "Blackstone"),
    ("blast_furnace", "Blast furnace", "Blast furnace"),
    ("blue_banner", "Blue banner", "Blue banner"),
    ("blue_bed", "Blue bed", "Blue bed"),
    ("blue_candle_cake", "Blue candle cake", "Blue candle cake"),
    ("blue_candle", "Blue candle", "Blue candle"),
    ("blue_carpet", "Blue carpet", "Blue carpet"),
    ("blue_concrete_powder", "Blue concrete powder", "Blue concrete powder"),
    ("blue_concrete", "Blue concrete", "Blue concrete"),
    ("blue_glazed_terracotta", "Blue glazed terracotta", "Blue glazed terracotta"),
    ("blue_ice", "Blue ice", "Blue ice"),
    ("blue_orchid", "Blue orchid", "Blue orchid"),
    ("blue_shulker_box", "Blue shulker box", "Blue shulker box"),
    ("blue_stained_glass_pane", "Blue stained glass pane", "Blue stained glass pane"),
    ("blue_stained_glass", "Blue stained glass", "Blue stained glass"),
    ("blue_terracotta", "Blue terracotta", "Blue terracotta"),
    ("blue_wall_banner", "Blue wall banner", "Blue wall banner"),
    ("blue_wool", "Blue wool", "Blue wool"),
    ("bone_block", "Bone block", "Bone block"),
    ("bookshelf", "Bookshelf", "Bookshelf"),
    ("brain_coral_block", "Brain coral block", "Brain coral block"),
    ("brain_coral_fan", "Brain coral fan", "Brain coral fan"),
    ("brain_coral_wall_fan", "Brain coral wall fan", "Brain coral wall fan"),
    ("brain_coral", "Brain coral", "Brain coral"),
    ("brewing_stand", "Brewing stand", "Brewing stand"),
    ("brick_slab", "Brick slab", "Brick slab"),
    ("brick_stairs", "Brick stairs", "Brick stairs"),
    ("brick_wall", "Brick wall", "Brick wall"),
    ("bricks", "Bricks", "Bricks"),
    ("brown_banner", "Brown banner", "Brown banner"),
    ("brown_bed", "Brown bed", "Brown bed"),
    ("brown_candle_cake", "Brown candle cake", "Brown candle cake"),
    ("brown_candle", "Brown candle", "Brown candle"),
    ("brown_carpet", "Brown carpet", "Brown carpet"),
    ("brown_concrete_powder", "Brown concrete powder", "Brown concrete powder"),
    ("brown_concrete", "Brown concrete", "Brown concrete"),
    ("brown_glazed_terracotta", "Brown glazed terracotta", "Brown glazed terracotta"),
    ("brown_mushroom_block", "Brown mushroom block", "Brown mushroom block"),
    ("brown_mushroom", "Brown mushroom", "Brown mushroom"),
    ("brown_shulker_box", "Brown shulker box", "Brown shulker box"),
    ("brown_stained_glass_pane", "Brown stained glass pane", "Brown stained glass pane"),
    ("brown_stained_glass", "Brown stained glass", "Brown stained glass"),
    ("brown_terracotta", "Brown terracotta", "Brown terracotta"),
    ("brown_wall_banner", "Brown wall banner", "Brown wall banner"),
    ("brown_wool", "Brown wool", "Brown wool"),
    ("bubble_column", "Bubble column", "Bubble column"),
    ("bubble_coral_block", "Bubble coral block", "Bubble coral block"),
    ("bubble_coral_fan", "Bubble coral fan", "Bubble coral fan"),
    ("bubble_coral_wall_fan", "Bubble coral wall fan", "Bubble coral wall fan"),
    ("bubble_coral", "Bubble coral", "Bubble coral"),
    ("budding_amethyst", "Budding amethyst", "Budding amethyst"),
    ("cactus", "Cactus", "Cactus"),
    ("cake", "Cake", "Cake"),
    ("calcite", "Calcite", "Calcite"),
    ("calibrated_sculk_sensor", "Calibrated sculk sensor", "Calibrated sculk sensor"),
    ("campfire", "Campfire", "Campfire"),
    ("candle_cake", "Candle cake", "Candle cake"),
    ("candle", "Candle", "Candle"),
    ("carrots", "Carrots", "Carrots"),
    ("cartography_table", "Cartography table", "Cartography table"),
    ("carved_pumpkin", "Carved pumpkin", "Carved pumpkin"),
    ("cauldron", "Cauldron", "Cauldron"),
    ("cave_air", "Cave air", "Cave air"),
    ("cave_vines_plant", "Cave vines plant", "Cave vines plant"),
    ("cave_vines", "Cave vines", "Cave vines"),
    ("chain_command_block", "Chain command block", "Chain command block"),
    ("chain", "Chain", "Chain"),
    ("cherry_button", "Cherry button", "Cherry button"),
    ("cherry_door", "Cherry door", "Cherry door"),
    ("cherry_fence_gate", "Cherry fence gate", "Cherry fence gate"),
    ("cherry_fence", "Cherry fence", "Cherry fence"),
    ("cherry_hanging_sign", "Cherry hanging sign", "Cherry hanging sign"),
    ("cherry_leaves", "Cherry leaves", "Cherry leaves"),
    ("cherry_log", "Cherry log", "Cherry log"),
    ("cherry_planks", "Cherry planks", "Cherry planks"),
    ("cherry_pressure_plate", "Cherry pressure plate", "Cherry pressure plate"),
    ("cherry_sapling", "Cherry sapling", "Cherry sapling"),
    ("cherry_sign", "Cherry sign", "Cherry sign"),
    ("cherry_slab", "Cherry slab", "Cherry slab"),
    ("cherry_stairs", "Cherry stairs", "Cherry stairs"),
    ("cherry_trapdoor", "Cherry trapdoor", "Cherry trapdoor"),
    ("cherry_wall_hanging_sign", "Cherry wall hanging sign", "Cherry wall hanging sign"),
    ("cherry_wall_sign", "Cherry wall sign", "Cherry wall sign"),
    ("cherry_wood", "Cherry wood", "Cherry wood"),
    ("chest", "Chest", "Chest"),
    ("chipped_anvil", "Chipped anvil", "Chipped anvil"),
    ("chiseled_bookshelf", "Chiseled bookshelf", "Chiseled bookshelf"),
    ("chiseled_deepslate", "Chiseled deepslate", "Chiseled deepslate"),
    ("chiseled_nether_bricks", "Chiseled nether bricks", "Chiseled nether bricks"),
    ("chiseled_polished_blackstone", "Chiseled polished blackstone", "Chiseled polished blackstone"),
    ("chiseled_quartz_block", "Chiseled quartz block", "Chiseled quartz block"),
    ("chiseled_red_sandstone", "Chiseled red sandstone", "Chiseled red sandstone"),
    ("chiseled_sandstone", "Chiseled sandstone", "Chiseled sandstone"),
    ("chiseled_stone_bricks", "Chiseled stone bricks", "Chiseled stone bricks"),
    ("chorus_flower", "Chorus flower", "Chorus flower"),
    ("chorus_plant", "Chorus plant", "Chorus plant"),
    ("clay", "Clay", "Clay"),
    ("coal_block", "Coal block", "Coal block"),
    ("coal_ore", "Coal ore", "Coal ore"),
    ("coarse_dirt", "Coarse dirt", "Coarse dirt"),
    ("cobbled_deepslate_slab", "Cobbled deepslate slab", "Cobbled deepslate slab"),
    ("cobbled_deepslate_stairs", "Cobbled deepslate stairs", "Cobbled deepslate stairs"),
    ("cobbled_deepslate_wall", "Cobbled deepslate wall", "Cobbled deepslate wall"),
    ("cobbled_deepslate", "Cobbled deepslate", "Cobbled deepslate"),
    ("cobblestone_slab", "Cobblestone slab", "Cobblestone slab"),
    ("cobblestone_stairs", "Cobblestone stairs", "Cobblestone stairs"),
    ("cobblestone_wall", "Cobblestone wall", "Cobblestone wall"),
    ("cobblestone", "Cobblestone", "Cobblestone"),
    ("cobweb", "Cobweb", "Cobweb"),
    ("cocoa", "Cocoa", "Cocoa"),
    ("command_block", "Command block", "Command block"),
    ("comparator", "Comparator", "Comparator"),
    ("composter", "Composter", "Composter"),
    ("conduit", "Conduit", "Conduit"),
    ("copper_block", "Copper block", "Copper block"),
    ("copper_ore", "Copper ore", "Copper ore"),
    ("cornflower", "Cornflower", "Cornflower"),
    ("cracked_deepslate_bricks", "Cracked deepslate bricks", "Cracked deepslate bricks"),
    ("cracked_deepslate_tiles", "Cracked deepslate tiles", "Cracked deepslate tiles"),
    ("cracked_nether_bricks", "Cracked nether bricks", "Cracked nether bricks"),
    ("cracked_polished_blackstone_bricks", "Cracked polished blackstone bricks", "Cracked polished blackstone bricks"),
    ("cracked_stone_bricks", "Cracked stone bricks", "Cracked stone bricks"),
    ("crafting_table", "Crafting table", "Crafting table"),
    ("creeper_head", "Creeper head", "Creeper head"),
    ("creeper_wall_head", "Creeper wall head", "Creeper wall head"),
    ("crimson_button", "Crimson button", "Crimson button"),
    ("crimson_door", "Crimson door", "Crimson door"),
    ("crimson_fence_gate", "Crimson fence gate", "Crimson fence gate"),
    ("crimson_fence", "Crimson fence", "Crimson fence"),
    ("crimson_fungus", "Crimson fungus", "Crimson fungus"),
    ("crimson_hanging_sign", "Crimson hanging sign", "Crimson hanging sign"),
    ("crimson_hyphae", "Crimson hyphae", "Crimson hyphae"),
    ("crimson_nylium", "Crimson nylium", "Crimson nylium"),
    ("crimson_planks", "Crimson planks", "Crimson planks"),
    ("crimson_pressure_plate", "Crimson pressure plate", "Crimson pressure plate"),
    ("crimson_roots", "Crimson roots", "Crimson roots"),
    ("crimson_sign", "Crimson sign", "Crimson sign"),
    ("crimson_slab", "Crimson slab", "Crimson slab"),
    ("crimson_stairs", "Crimson stairs", "Crimson stairs"),
    ("crimson_stem", "Crimson stem", "Crimson stem"),
    ("crimson_trapdoor", "Crimson trapdoor", "Crimson trapdoor"),
    ("crimson_wall_hanging_sign", "Crimson wall hanging sign", "Crimson wall hanging sign"),
    ("crimson_wall_sign", "Crimson wall sign", "Crimson wall sign"),
    ("crying_obsidian", "Crying obsidian", "Crying obsidian"),
    ("cut_copper_slab", "Cut copper slab", "Cut copper slab"),
    ("cut_copper_stairs", "Cut copper stairs", "Cut copper stairs"),
    ("cut_copper", "Cut copper", "Cut copper"),
    ("cut_red_sandstone_slab", "Cut red sandstone slab", "Cut red sandstone slab"),
    ("cut_red_sandstone", "Cut red sandstone", "Cut red sandstone"),
    ("cut_sandstone_slab", "Cut sandstone slab", "Cut sandstone slab"),
    ("cut_sandstone", "Cut sandstone", "Cut sandstone"),
    ("cyan_banner", "Cyan banner", "Cyan banner"),
    ("cyan_bed", "Cyan bed", "Cyan bed"),
    ("cyan_candle_cake", "Cyan candle cake", "Cyan candle cake"),
    ("cyan_candle", "Cyan candle", "Cyan candle"),
    ("cyan_carpet", "Cyan carpet", "Cyan carpet"),
    ("cyan_concrete_powder", "Cyan concrete powder", "Cyan concrete powder"),
    ("cyan_concrete", "Cyan concrete", "Cyan concrete"),
    ("cyan_glazed_terracotta", "Cyan glazed terracotta", "Cyan glazed terracotta"),
    ("cyan_shulker_box", "Cyan shulker box", "Cyan shulker box"),
    ("cyan_stained_glass_pane", "Cyan stained glass pane", "Cyan stained glass pane"),
    ("cyan_stained_glass", "Cyan stained glass", "Cyan stained glass"),
    ("cyan_terracotta", "Cyan terracotta", "Cyan terracotta"),
    ("cyan_wall_banner", "Cyan wall banner", "Cyan wall banner"),
    ("cyan_wool", "Cyan wool", "Cyan wool"),
    ("damaged_anvil", "Damaged anvil", "Damaged anvil"),
    ("dandelion", "Dandelion", "Dandelion"),
    ("dark_oak_button", "Dark oak button", "Dark oak button"),
    ("dark_oak_door", "Dark oak door", "Dark oak door"),
    ("dark_oak_fence_gate", "Dark oak fence gate", "Dark oak fence gate"),
    ("dark_oak_fence", "Dark oak fence", "Dark oak fence"),
    ("dark_oak_hanging_sign", "Dark oak hanging sign", "Dark oak hanging sign"),
    ("dark_oak_leaves", "Dark oak leaves", "Dark oak leaves"),
    ("dark_oak_log", "Dark oak log", "Dark oak log"),
    ("dark_oak_planks", "Dark oak planks", "Dark oak planks"),
    ("dark_oak_pressure_plate", "Dark oak pressure plate", "Dark oak pressure plate"),
    ("dark_oak_sapling", "Dark oak sapling", "Dark oak sapling"),
    ("dark_oak_sign", "Dark oak sign", "Dark oak sign"),
    ("dark_oak_slab", "Dark oak slab", "Dark oak slab"),
    ("dark_oak_stairs", "Dark oak stairs", "Dark oak stairs"),
    ("dark_oak_trapdoor", "Dark oak trapdoor", "Dark oak trapdoor"),
    ("dark_oak_wall_hanging_sign", "Dark oak wall hanging sign", "Dark oak wall hanging sign"),
    ("dark_oak_wall_sign", "Dark oak wall sign", "Dark oak wall sign"),
    ("dark_oak_wood", "Dark oak wood", "Dark oak wood"),
    ("dark_prismarine_slab", "Dark prismarine slab", "Dark prismarine slab"),
    ("dark_prismarine_stairs", "Dark prismarine stairs", "Dark prismarine stairs"),
    ("dark_prismarine", "Dark prismarine", "Dark prismarine"),
    ("daylight_detector", "Daylight detector", "Daylight detector"),
    ("dead_brain_coral_block", "Dead brain coral block", "Dead brain coral block"),
    ("dead_brain_coral_fan", "Dead brain coral fan", "Dead brain coral fan"),
    ("dead_brain_coral_wall_fan", "Dead brain coral wall fan", "Dead brain coral wall fan"),
    ("dead_brain_coral", "Dead brain coral", "Dead brain coral"),
    ("dead_bubble_coral_block", "Dead bubble coral block", "Dead bubble coral block"),
    ("dead_bubble_coral_fan", "Dead bubble coral fan", "Dead bubble coral fan"),
    ("dead_bubble_coral_wall_fan", "Dead bubble coral wall fan", "Dead bubble coral wall fan"),
    ("dead_bubble_coral", "Dead bubble coral", "Dead bubble coral"),
    ("dead_bush", "Dead bush", "Dead bush"),
    ("dead_fire_coral_block", "Dead fire coral block", "Dead fire coral block"),
    ("dead_fire_coral_fan", "Dead fire coral fan", "Dead fire coral fan"),
    ("dead_fire_coral_wall_fan", "Dead fire coral wall fan", "Dead fire coral wall fan"),
    ("dead_fire_coral", "Dead fire coral", "Dead fire coral"),
    ("dead_horn_coral_block", "Dead horn coral block", "Dead horn coral block"),
    ("dead_horn_coral_fan", "Dead horn coral fan", "Dead horn coral fan"),
    ("dead_horn_coral_wall_fan", "Dead horn coral wall fan", "Dead horn coral wall fan"),
    ("dead_horn_coral", "Dead horn coral", "Dead horn coral"),
    ("dead_tube_coral_block", "Dead tube coral block", "Dead tube coral block"),
    ("dead_tube_coral_fan", "Dead tube coral fan", "Dead tube coral fan"),
    ("dead_tube_coral_wall_fan", "Dead tube coral wall fan", "Dead tube coral wall fan"),
    ("dead_tube_coral", "Dead tube coral", "Dead tube coral"),
    ("decorated_pot", "Decorated pot", "Decorated pot"),
    ("deepslate_brick_slab", "Deepslate brick slab", "Deepslate brick slab"),
    ("deepslate_brick_stairs", "Deepslate brick stairs", "Deepslate brick stairs"),
    ("deepslate_brick_wall", "Deepslate brick wall", "Deepslate brick wall"),
    ("deepslate_bricks", "Deepslate bricks", "Deepslate bricks"),
    ("deepslate_coal_ore", "Deepslate coal ore", "Deepslate coal ore"),
    ("deepslate_copper_ore", "Deepslate copper ore", "Deepslate copper ore"),
    ("deepslate_diamond_ore", "Deepslate diamond ore", "Deepslate diamond ore"),
    ("deepslate_emerald_ore", "Deepslate emerald ore", "Deepslate emerald ore"),
    ("deepslate_gold_ore", "Deepslate gold ore", "Deepslate gold ore"),
    ("deepslate_iron_ore", "Deepslate iron ore", "Deepslate iron ore"),
    ("deepslate_lapis_ore", "Deepslate lapis ore", "Deepslate lapis ore"),
    ("deepslate_redstone_ore", "Deepslate redstone ore", "Deepslate redstone ore"),
    ("deepslate_tile_slab", "Deepslate tile slab", "Deepslate tile slab"),
    ("deepslate_tile_stairs", "Deepslate tile stairs", "Deepslate tile stairs"),
    ("deepslate_tile_wall", "Deepslate tile wall", "Deepslate tile wall"),
    ("deepslate_tiles", "Deepslate tiles", "Deepslate tiles"),
    ("deepslate", "Deepslate", "Deepslate"),
    ("detector_rail", "Detector rail", "Detector rail"),
    ("diamond_block", "Diamond block", "Diamond block"),
    ("diamond_ore", "Diamond ore", "Diamond ore"),
    ("diorite_slab", "Diorite slab", "Diorite slab"),
    ("diorite_stairs", "Diorite stairs", "Diorite stairs"),
    ("diorite_wall", "Diorite wall", "Diorite wall"),
    ("diorite", "Diorite", "Diorite"),
    ("dirt_path", "Dirt path", "Dirt path"),
    ("dirt", "Dirt", "Dirt"),
    ("dispenser", "Dispenser", "Dispenser"),
    ("dragon_egg", "Dragon egg", "Dragon egg"),
    ("dragon_head", "Dragon head", "Dragon head"),
    ("dragon_wall_head", "Dragon wall head", "Dragon wall head"),
    ("dried_kelp_block", "Dried kelp block", "Dried kelp block"),
    ("dripstone_block", "Dripstone block", "Dripstone block"),
    ("dropper", "Dropper", "Dropper"),
    ("emerald_block", "Emerald block", "Emerald block"),
    ("emerald_ore", "Emerald ore", "Emerald ore"),
    ("enchanting_table", "Enchanting table", "Enchanting table"),
    ("end_gateway", "End gateway", "End gateway"),
    ("end_portal_frame", "End portal frame", "End portal frame"),
    ("end_portal", "End portal", "End portal"),
    ("end_rod", "End rod", "End rod"),
    ("end_stone_brick_slab", "End stone brick slab", "End stone brick slab"),
    ("end_stone_brick_stairs", "End stone brick stairs", "End stone brick stairs"),
    ("end_stone_brick_wall", "End stone brick wall", "End stone brick wall"),
    ("end_stone_bricks", "End stone bricks", "End stone bricks"),
    ("end_stone", "End stone", "End stone"),
    ("ender_chest", "Ender chest", "Ender chest"),
    ("exposed_copper", "Exposed copper", "Exposed copper"),
    ("exposed_cut_copper_slab", "Exposed cut copper slab", "Exposed cut copper slab"),
    ("exposed_cut_copper_stairs", "Exposed cut copper stairs", "Exposed cut copper stairs"),
    ("exposed_cut_copper", "Exposed cut copper", "Exposed cut copper"),
    ("farmland", "Farmland", "Farmland"),
    ("fern", "Fern", "Fern"),
    ("fire_coral_block", "Fire coral block", "Fire coral block"),
    ("fire_coral_fan", "Fire coral fan", "Fire coral fan"),
    ("fire_coral_wall_fan", "Fire coral wall fan", "Fire coral wall fan"),
    ("fire_coral", "Fire coral", "Fire coral"),
    ("fire", "Fire", "Fire"),
    ("fletching_table", "Fletching table", "Fletching table"),
    ("flower_pot", "Flower pot", "Flower pot"),
    ("flowering_azalea_leaves", "Flowering azalea leaves", "Flowering azalea leaves"),
    ("flowering_azalea", "Flowering azalea", "Flowering azalea"),
    ("frogspawn", "Frogspawn", "Frogspawn"),
    ("frosted_ice", "Frosted ice", "Frosted ice"),
    ("furnace", "Furnace", "Furnace"),
    ("gilded_blackstone", "Gilded blackstone", "Gilded blackstone"),
    ("glass_pane", "Glass pane", "Glass pane"),
    ("glass", "Glass", "Glass"),
    ("glow_item_frame", "Glow item frame", "Glow item frame"),
    ("glow_lichen", "Glow lichen", "Glow lichen"),
    ("glowstone", "Glowstone", "Glowstone"),
    ("gold_block", "Gold block", "Gold block"),
    ("gold_ore", "Gold ore", "Gold ore"),
    ("granite_slab", "Granite slab", "Granite slab"),
    ("granite_stairs", "Granite stairs", "Granite stairs"),
    ("granite_wall", "Granite wall", "Granite wall"),
    ("granite", "Granite", "Granite"),
    ("grass_block", "Grass block", "Grass block"),
    ("grass", "Grass", "Grass"),
    ("gravel", "Gravel", "Gravel"),
    ("gray_banner", "Gray banner", "Gray banner"),
    ("gray_bed", "Gray bed", "Gray bed"),
    ("gray_candle_cake", "Gray candle cake", "Gray candle cake"),
    ("gray_candle", "Gray candle", "Gray candle"),
    ("gray_carpet", "Gray carpet", "Gray carpet"),
    ("gray_concrete_powder", "Gray concrete powder", "Gray concrete powder"),
    ("gray_concrete", "Gray concrete", "Gray concrete"),
    ("gray_glazed_terracotta", "Gray glazed terracotta", "Gray glazed terracotta"),
    ("gray_shulker_box", "Gray shulker box", "Gray shulker box"),
    ("gray_stained_glass_pane", "Gray stained glass pane", "Gray stained glass pane"),
    ("gray_stained_glass", "Gray stained glass", "Gray stained glass"),
    ("gray_terracotta", "Gray terracotta", "Gray terracotta"),
    ("gray_wall_banner", "Gray wall banner", "Gray wall banner"),
    ("gray_wool", "Gray wool", "Gray wool"),
    ("green_banner", "Green banner", "Green banner"),
    ("green_bed", "Green bed", "Green bed"),
    ("green_candle_cake", "Green candle cake", "Green candle cake"),
    ("green_candle", "Green candle", "Green candle"),
    ("green_carpet", "Green carpet", "Green carpet"),
    ("green_concrete_powder", "Green concrete powder", "Green concrete powder"),
    ("green_concrete", "Green concrete", "Green concrete"),
    ("green_glazed_terracotta", "Green glazed terracotta", "Green glazed terracotta"),
    ("green_shulker_box", "Green shulker box", "Green shulker box"),
    ("green_stained_glass_pane", "Green stained glass pane", "Green stained glass pane"),
    ("green_stained_glass", "Green stained glass", "Green stained glass"),
    ("green_terracotta", "Green terracotta", "Green terracotta"),
    ("green_wall_banner", "Green wall banner", "Green wall banner"),
    ("green_wool", "Green wool", "Green wool"),
    ("grindstone", "Grindstone", "Grindstone"),
    ("hanging_roots", "Hanging roots", "Hanging roots"),
    ("hay_block", "Hay block", "Hay block"),
    ("heavy_weighted_pressure_plate", "Heavy weighted pressure plate", "Heavy weighted pressure plate"),
    ("honey_block", "Honey block", "Honey block"),
    ("honeycomb_block", "Honeycomb block", "Honeycomb block"),
    ("hopper", "Hopper", "Hopper"),
    ("horn_coral_block", "Horn coral block", "Horn coral block"),
    ("horn_coral_fan", "Horn coral fan", "Horn coral fan"),
    ("horn_coral_wall_fan", "Horn coral wall fan", "Horn coral wall fan"),
    ("horn_coral", "Horn coral", "Horn coral"),
    ("ice", "Ice", "Ice"),
    ("infested_chiseled_stone_bricks", "Infested chiseled stone bricks", "Infested chiseled stone bricks"),
    ("infested_cobblestone", "Infested cobblestone", "Infested cobblestone"),
    ("infested_cracked_stone_bricks", "Infested cracked stone bricks", "Infested cracked stone bricks"),
    ("infested_deepslate", "Infested deepslate", "Infested deepslate"),
    ("infested_mossy_stone_bricks", "Infested mossy stone bricks", "Infested mossy stone bricks"),
    ("infested_stone_bricks", "Infested stone bricks", "Infested stone bricks"),
    ("infested_stone", "Infested stone", "Infested stone"),
    ("iron_bars", "Iron bars", "Iron bars"),
    ("iron_block", "Iron block", "Iron block"),
    ("iron_door", "Iron door", "Iron door"),
    ("iron_ore", "Iron ore", "Iron ore"),
    ("iron_trapdoor", "Iron trapdoor", "Iron trapdoor"),
    ("item_frame", "Item frame", "Item frame"),
    ("jack_o_lantern", "Jack o lantern", "Jack o lantern"),
    ("jigsaw", "Jigsaw", "Jigsaw"),
    ("jukebox", "Jukebox", "Jukebox"),
    ("jungle_button", "Jungle button", "Jungle button"),
    ("jungle_door", "Jungle door", "Jungle door"),
    ("jungle_fence_gate", "Jungle fence gate", "Jungle fence gate"),
    ("jungle_fence", "Jungle fence", "Jungle fence"),
    ("jungle_hanging_sign", "Jungle hanging sign", "Jungle hanging sign"),
    ("jungle_leaves", "Jungle leaves", "Jungle leaves"),
    ("jungle_log", "Jungle log", "Jungle log"),
    ("jungle_planks", "Jungle planks", "Jungle planks"),
    ("jungle_pressure_plate", "Jungle pressure plate", "Jungle pressure plate"),
    ("jungle_sapling", "Jungle sapling", "Jungle sapling"),
    ("jungle_sign", "Jungle sign", "Jungle sign"),
    ("jungle_slab", "Jungle slab", "Jungle slab"),
    ("jungle_stairs", "Jungle stairs", "Jungle stairs"),
    ("jungle_trapdoor", "Jungle trapdoor", "Jungle trapdoor"),
    ("jungle_wall_hanging_sign", "Jungle wall hanging sign", "Jungle wall hanging sign"),
    ("jungle_wall_sign", "Jungle wall sign", "Jungle wall sign"),
    ("jungle_wood", "Jungle wood", "Jungle wood"),
    ("kelp_plant", "Kelp plant", "Kelp plant"),
    ("kelp", "Kelp", "Kelp"),
    ("ladder", "Ladder", "Ladder"),
    ("lantern", "Lantern", "Lantern"),
    ("lapis_block", "Lapis block", "Lapis block"),
    ("lapis_ore", "Lapis ore", "Lapis ore"),
    ("large_amethyst_bud", "Large amethyst bud", "Large amethyst bud"),
    ("large_fern", "Large fern", "Large fern"),
    ("lava_cauldron", "Lava cauldron", "Lava cauldron"),
    ("lava", "Lava", "Lava"),
    ("lectern", "Lectern", "Lectern"),
    ("lever", "Lever", "Lever"),
    ("light_blue_banner", "Light blue banner", "Light blue banner"),
    ("light_blue_bed", "Light blue bed", "Light blue bed"),
    ("light_blue_candle_cake", "Light blue candle cake", "Light blue candle cake"),
    ("light_blue_candle", "Light blue candle", "Light blue candle"),
    ("light_blue_carpet", "Light blue carpet", "Light blue carpet"),
    ("light_blue_concrete_powder", "Light blue concrete powder", "Light blue concrete powder"),
    ("light_blue_concrete", "Light blue concrete", "Light blue concrete"),
    ("light_blue_glazed_terracotta", "Light blue glazed terracotta", "Light blue glazed terracotta"),
    ("light_blue_shulker_box", "Light blue shulker box", "Light blue shulker box"),
    ("light_blue_stained_glass_pane", "Light blue stained glass pane", "Light blue stained glass pane"),
    ("light_blue_stained_glass", "Light blue stained glass", "Light blue stained glass"),
    ("light_blue_terracotta", "Light blue terracotta", "Light blue terracotta"),
    ("light_blue_wall_banner", "Light blue wall banner", "Light blue wall banner"),
    ("light_blue_wool", "Light blue wool", "Light blue wool"),
    ("light_gray_banner", "Light gray banner", "Light gray banner"),
    ("light_gray_bed", "Light gray bed", "Light gray bed"),
    ("light_gray_candle_cake", "Light gray candle cake", "Light gray candle cake"),
    ("light_gray_candle", "Light gray candle", "Light gray candle"),
    ("light_gray_carpet", "Light gray carpet", "Light gray carpet"),
    ("light_gray_concrete_powder", "Light gray concrete powder", "Light gray concrete powder"),
    ("light_gray_concrete", "Light gray concrete", "Light gray concrete"),
    ("light_gray_glazed_terracotta", "Light gray glazed terracotta", "Light gray glazed terracotta"),
    ("light_gray_shulker_box", "Light gray shulker box", "Light gray shulker box"),
    ("light_gray_stained_glass_pane", "Light gray stained glass pane", "Light gray stained glass pane"),
    ("light_gray_stained_glass", "Light gray stained glass", "Light gray stained glass"),
    ("light_gray_terracotta", "Light gray terracotta", "Light gray terracotta"),
    ("light_gray_wall_banner", "Light gray wall banner", "Light gray wall banner"),
    ("light_gray_wool", "Light gray wool", "Light gray wool"),
    ("light_weighted_pressure_plate", "Light weighted pressure plate", "Light weighted pressure plate"),
    ("light", "Light", "Light"),
    ("lightning_rod", "Lightning rod", "Lightning rod"),
    ("lilac", "Lilac", "Lilac"),
    ("lily_of_the_valley", "Lily of the valley", "Lily of the valley"),
    ("lily_pad", "Lily pad", "Lily pad"),
    ("lime_banner", "Lime banner", "Lime banner"),
    ("lime_bed", "Lime bed", "Lime bed"),
    ("lime_candle_cake", "Lime candle cake", "Lime candle cake"),
    ("lime_candle", "Lime candle", "Lime candle"),
    ("lime_carpet", "Lime carpet", "Lime carpet"),
    ("lime_concrete_powder", "Lime concrete powder", "Lime concrete powder"),
    ("lime_concrete", "Lime concrete", "Lime concrete"),
    ("lime_glazed_terracotta", "Lime glazed terracotta", "Lime glazed terracotta"),
    ("lime_shulker_box", "Lime shulker box", "Lime shulker box"),
    ("lime_stained_glass_pane", "Lime stained glass pane", "Lime stained glass pane"),
    ("lime_stained_glass", "Lime stained glass", "Lime stained glass"),
    ("lime_terracotta", "Lime terracotta", "Lime terracotta"),
    ("lime_wall_banner", "Lime wall banner", "Lime wall banner"),
    ("lime_wool", "Lime wool", "Lime wool"),
    ("lodestone", "Lodestone", "Lodestone"),
    ("loom", "Loom", "Loom"),
    ("magenta_banner", "Magenta banner", "Magenta banner"),
    ("magenta_bed", "Magenta bed", "Magenta bed"),
    ("magenta_candle_cake", "Magenta candle cake", "Magenta candle cake"),
    ("magenta_candle", "Magenta candle", "Magenta candle"),
    ("magenta_carpet", "Magenta carpet", "Magenta carpet"),
    ("magenta_concrete_powder", "Magenta concrete powder", "Magenta concrete powder"),
    ("magenta_concrete", "Magenta concrete", "Magenta concrete"),
    ("magenta_glazed_terracotta", "Magenta glazed terracotta", "Magenta glazed terracotta"),
    ("magenta_shulker_box", "Magenta shulker box", "Magenta shulker box"),
    ("magenta_stained_glass_pane", "Magenta stained glass pane", "Magenta stained glass pane"),
    ("magenta_stained_glass", "Magenta stained glass", "Magenta stained glass"),
    ("magenta_terracotta", "Magenta terracotta", "Magenta terracotta"),
    ("magenta_wall_banner", "Magenta wall banner", "Magenta wall banner"),
    ("magenta_wool", "Magenta wool", "Magenta wool"),
    ("magma_block", "Magma block", "Magma block"),
    ("mangrove_button", "Mangrove button", "Mangrove button"),
    ("mangrove_door", "Mangrove door", "Mangrove door"),
    ("mangrove_fence_gate", "Mangrove fence gate", "Mangrove fence gate"),
    ("mangrove_fence", "Mangrove fence", "Mangrove fence"),
    ("mangrove_hanging_sign", "Mangrove hanging sign", "Mangrove hanging sign"),
    ("mangrove_leaves", "Mangrove leaves", "Mangrove leaves"),
    ("mangrove_log", "Mangrove log", "Mangrove log"),
    ("mangrove_planks", "Mangrove planks", "Mangrove planks"),
    ("mangrove_pressure_plate", "Mangrove pressure plate", "Mangrove pressure plate"),
    ("mangrove_propagule", "Mangrove propagule", "Mangrove propagule"),
    ("mangrove_roots", "Mangrove roots", "Mangrove roots"),
    ("mangrove_sign", "Mangrove sign", "Mangrove sign"),
    ("mangrove_slab", "Mangrove slab", "Mangrove slab"),
    ("mangrove_stairs", "Mangrove stairs", "Mangrove stairs"),
    ("mangrove_trapdoor", "Mangrove trapdoor", "Mangrove trapdoor"),
    ("mangrove_wall_hanging_sign", "Mangrove wall hanging sign", "Mangrove wall hanging sign"),
    ("mangrove_wall_sign", "Mangrove wall sign", "Mangrove wall sign"),
    ("mangrove_wood", "Mangrove wood", "Mangrove wood"),
    ("medium_amethyst_bud", "Medium amethyst bud", "Medium amethyst bud"),
    ("melon_stem", "Melon stem", "Melon stem"),
    ("melon", "Melon", "Melon"),
    ("moss_block", "Moss block", "Moss block"),
    ("moss_carpet", "Moss carpet", "Moss carpet"),
    ("mossy_cobblestone_slab", "Mossy cobblestone slab", "Mossy cobblestone slab"),
    ("mossy_cobblestone_stairs", "Mossy cobblestone stairs", "Mossy cobblestone stairs"),
    ("mossy_cobblestone_wall", "Mossy cobblestone wall", "Mossy cobblestone wall"),
    ("mossy_cobblestone", "Mossy cobblestone", "Mossy cobblestone"),
    ("mossy_stone_brick_slab", "Mossy stone brick slab", "Mossy stone brick slab"),
    ("mossy_stone_brick_stairs", "Mossy stone brick stairs", "Mossy stone brick stairs"),
    ("mossy_stone_brick_wall", "Mossy stone brick wall", "Mossy stone brick wall"),
    ("mossy_stone_bricks", "Mossy stone bricks", "Mossy stone bricks"),
    ("moving_piston", "Moving piston", "Moving piston"),
    ("mud_brick_slab", "Mud brick slab", "Mud brick slab"),
    ("mud_brick_stairs", "Mud brick stairs", "Mud brick stairs"),
    ("mud_brick_wall", "Mud brick wall", "Mud brick wall"),
    ("mud_bricks", "Mud bricks", "Mud bricks"),
    ("mud", "Mud", "Mud"),
    ("muddy_mangrove_roots", "Muddy mangrove roots", "Muddy mangrove roots"),
    ("mushroom_stem", "Mushroom stem", "Mushroom stem"),
    ("mycelium", "Mycelium", "Mycelium"),
    ("nether_brick_fence", "Nether brick fence", "Nether brick fence"),
    ("nether_brick_slab", "Nether brick slab", "Nether brick slab"),
    ("nether_brick_stairs", "Nether brick stairs", "Nether brick stairs"),
    ("nether_brick_wall", "Nether brick wall", "Nether brick wall"),
    ("nether_bricks", "Nether bricks", "Nether bricks"),
    ("nether_gold_ore", "Nether gold ore", "Nether gold ore"),
    ("nether_portal", "Nether portal", "Nether portal"),
    ("nether_quartz_ore", "Nether quartz ore", "Nether quartz ore"),
    ("nether_sprouts", "Nether sprouts", "Nether sprouts"),
    ("nether_wart_block", "Nether wart block", "Nether wart block"),
    ("nether_wart", "Nether wart", "Nether wart"),
    ("netherite_block", "Netherite block", "Netherite block"),
    ("netherrack", "Netherrack", "Netherrack"),
    ("note_block", "Note block", "Note block"),
    ("oak_button", "Oak button", "Oak button"),
    ("oak_door", "Oak door", "Oak door"),
    ("oak_fence_gate", "Oak fence gate", "Oak fence gate"),
    ("oak_fence", "Oak fence", "Oak fence"),
    ("oak_hanging_sign", "Oak hanging sign", "Oak hanging sign"),
    ("oak_leaves", "Oak leaves", "Oak leaves"),
    ("oak_log", "Oak log", "Oak log"),
    ("oak_planks", "Oak planks", "Oak planks"),
    ("oak_pressure_plate", "Oak pressure plate", "Oak pressure plate"),
    ("oak_sapling", "Oak sapling", "Oak sapling"),
    ("oak_sign", "Oak sign", "Oak sign"),
    ("oak_slab", "Oak slab", "Oak slab"),
    ("oak_stairs", "Oak stairs", "Oak stairs"),
    ("oak_trapdoor", "Oak trapdoor", "Oak trapdoor"),
    ("oak_wall_hanging_sign", "Oak wall hanging sign", "Oak wall hanging sign"),
    ("oak_wall_sign", "Oak wall sign", "Oak wall sign"),
    ("oak_wood", "Oak wood", "Oak wood"),
    ("observer", "Observer", "Observer"),
    ("obsidian", "Obsidian", "Obsidian"),
    ("ochre_froglight", "Ochre froglight", "Ochre froglight"),
    ("orange_banner", "Orange banner", "Orange banner"),
    ("orange_bed", "Orange bed", "Orange bed"),
    ("orange_candle_cake", "Orange candle cake", "Orange candle cake"),
    ("orange_candle", "Orange candle", "Orange candle"),
    ("orange_carpet", "Orange carpet", "Orange carpet"),
    ("orange_concrete_powder", "Orange concrete powder", "Orange concrete powder"),
    ("orange_concrete", "Orange concrete", "Orange concrete"),
    ("orange_glazed_terracotta", "Orange glazed terracotta", "Orange glazed terracotta"),
    ("orange_shulker_box", "Orange shulker box", "Orange shulker box"),
    ("orange_stained_glass_pane", "Orange stained glass pane", "Orange stained glass pane"),
    ("orange_stained_glass", "Orange stained glass", "Orange stained glass"),
    ("orange_terracotta", "Orange terracotta", "Orange terracotta"),
    ("orange_tulip", "Orange tulip", "Orange tulip"),
    ("orange_wall_banner", "Orange wall banner", "Orange wall banner"),
    ("orange_wool", "Orange wool", "Orange wool"),
    ("oxeye_daisy", "Oxeye daisy", "Oxeye daisy"),
    ("oxidized_copper", "Oxidized copper", "Oxidized copper"),
    ("oxidized_cut_copper_slab", "Oxidized cut copper slab", "Oxidized cut copper slab"),
    ("oxidized_cut_copper_stairs", "Oxidized cut copper stairs", "Oxidized cut copper stairs"),
    ("oxidized_cut_copper", "Oxidized cut copper", "Oxidized cut copper"),
    ("packed_ice", "Packed ice", "Packed ice"),
    ("packed_mud", "Packed mud", "Packed mud"),
    ("pearlescent_froglight", "Pearlescent froglight", "Pearlescent froglight"),
    ("peony", "Peony", "Peony"),
    ("petrified_oak_slab", "Petrified oak slab", "Petrified oak slab"),
    ("piglin_head", "Piglin head", "Piglin head"),
    ("piglin_wall_head", "Piglin wall head", "Piglin wall head"),
    ("pink_banner", "Pink banner", "Pink banner"),
    ("pink_bed", "Pink bed", "Pink bed"),
    ("pink_candle_cake", "Pink candle cake", "Pink candle cake"),
    ("pink_candle", "Pink candle", "Pink candle"),
    ("pink_carpet", "Pink carpet", "Pink carpet"),
    ("pink_concrete_powder", "Pink concrete powder", "Pink concrete powder"),
    ("pink_concrete", "Pink concrete", "Pink concrete"),
    ("pink_glazed_terracotta", "Pink glazed terracotta", "Pink glazed terracotta"),
    ("pink_petals", "Pink petals", "Pink petals"),
    ("pink_shulker_box", "Pink shulker box", "Pink shulker box"),
    ("pink_stained_glass_pane", "Pink stained glass pane", "Pink stained glass pane"),
    ("pink_stained_glass", "Pink stained glass", "Pink stained glass"),
    ("pink_terracotta", "Pink terracotta", "Pink terracotta"),
    ("pink_tulip", "Pink tulip", "Pink tulip"),
    ("pink_wall_banner", "Pink wall banner", "Pink wall banner"),
    ("pink_wool", "Pink wool", "Pink wool"),
    ("piston_head", "Piston head", "Piston head"),
    ("piston", "Piston", "Piston"),
    ("pitcher_crop", "Pitcher crop", "Pitcher crop"),
    ("pitcher_plant", "Pitcher plant", "Pitcher plant"),
    ("player_head", "Player head", "Player head"),
    ("player_wall_head", "Player wall head", "Player wall head"),
    ("podzol", "Podzol", "Podzol"),
    ("pointed_dripstone", "Pointed dripstone", "Pointed dripstone"),
    ("polished_andesite_slab", "Polished andesite slab", "Polished andesite slab"),
    ("polished_andesite_stairs", "Polished andesite stairs", "Polished andesite stairs"),
    ("polished_andesite", "Polished andesite", "Polished andesite"),
    ("polished_basalt", "Polished basalt", "Polished basalt"),
    ("polished_blackstone_brick_slab", "Polished blackstone brick slab", "Polished blackstone brick slab"),
    ("polished_blackstone_brick_stairs", "Polished blackstone brick stairs", "Polished blackstone brick stairs"),
    ("polished_blackstone_brick_wall", "Polished blackstone brick wall", "Polished blackstone brick wall"),
    ("polished_blackstone_bricks", "Polished blackstone bricks", "Polished blackstone bricks"),
    ("polished_blackstone_button", "Polished blackstone button", "Polished blackstone button"),
    ("polished_blackstone_pressure_plate", "Polished blackstone pressure plate", "Polished blackstone pressure plate"),
    ("polished_blackstone_slab", "Polished blackstone slab", "Polished blackstone slab"),
    ("polished_blackstone_stairs", "Polished blackstone stairs", "Polished blackstone stairs"),
    ("polished_blackstone_wall", "Polished blackstone wall", "Polished blackstone wall"),
    ("polished_blackstone", "Polished blackstone", "Polished blackstone"),
    ("polished_deepslate_slab", "Polished deepslate slab", "Polished deepslate slab"),
    ("polished_deepslate_stairs", "Polished deepslate stairs", "Polished deepslate stairs"),
    ("polished_deepslate_wall", "Polished deepslate wall", "Polished deepslate wall"),
    ("polished_deepslate", "Polished deepslate", "Polished deepslate"),
    ("polished_diorite_slab", "Polished diorite slab", "Polished diorite slab"),
    ("polished_diorite_stairs", "Polished diorite stairs", "Polished diorite stairs"),
    ("polished_diorite", "Polished diorite", "Polished diorite"),
    ("polished_granite_slab", "Polished granite slab", "Polished granite slab"),
    ("polished_granite_stairs", "Polished granite stairs", "Polished granite stairs"),
    ("polished_granite", "Polished granite", "Polished granite"),
    ("poppy", "Poppy", "Poppy"),
    ("potatoes", "Potatoes", "Potatoes"),
    ("potted_acacia_sapling", "Potted acacia sapling", "Potted acacia sapling"),
    ("potted_allium", "Potted allium", "Potted allium"),
    ("potted_azalea_bush", "Potted azalea bush", "Potted azalea bush"),
    ("potted_azure_bluet", "Potted azure bluet", "Potted azure bluet"),
    ("potted_bamboo", "Potted bamboo", "Potted bamboo"),
    ("potted_birch_sapling", "Potted birch sapling", "Potted birch sapling"),
    ("potted_blue_orchid", "Potted blue orchid", "Potted blue orchid"),
    ("potted_brown_mushroom", "Potted brown mushroom", "Potted brown mushroom"),
    ("potted_cactus", "Potted cactus", "Potted cactus"),
    ("potted_cherry_sapling", "Potted cherry sapling", "Potted cherry sapling"),
    ("potted_cornflower", "Potted cornflower", "Potted cornflower"),
    ("potted_crimson_fungus", "Potted crimson fungus", "Potted crimson fungus"),
    ("potted_crimson_roots", "Potted crimson roots", "Potted crimson roots"),
    ("potted_dandelion", "Potted dandelion", "Potted dandelion"),
    ("potted_dark_oak_sapling", "Potted dark oak sapling", "Potted dark oak sapling"),
    ("potted_dead_bush", "Potted dead bush", "Potted dead bush"),
    ("potted_fern", "Potted fern", "Potted fern"),
    ("potted_flowering_azalea_bush", "Potted flowering azalea bush", "Potted flowering azalea bush"),
    ("potted_jungle_sapling", "Potted jungle sapling", "Potted jungle sapling"),
    ("potted_lily_of_the_valley", "Potted lily of the valley", "Potted lily of the valley"),
    ("potted_mangrove_propagule", "Potted mangrove propagule", "Potted mangrove propagule"),
    ("potted_oak_sapling", "Potted oak sapling", "Potted oak sapling"),
    ("potted_orange_tulip", "Potted orange tulip", "Potted orange tulip"),
    ("potted_oxeye_daisy", "Potted oxeye daisy", "Potted oxeye daisy"),
    ("potted_pink_tulip", "Potted pink tulip", "Potted pink tulip"),
    ("potted_poppy", "Potted poppy", "Potted poppy"),
    ("potted_red_mushroom", "Potted red mushroom", "Potted red mushroom"),
    ("potted_red_tulip", "Potted red tulip", "Potted red tulip"),
    ("potted_spruce_sapling", "Potted spruce sapling", "Potted spruce sapling"),
    ("potted_torchflower", "Potted torchflower", "Potted torchflower"),
    ("potted_warped_fungus", "Potted warped fungus", "Potted warped fungus"),
    ("potted_warped_roots", "Potted warped roots", "Potted warped roots"),
    ("potted_white_tulip", "Potted white tulip", "Potted white tulip"),
    ("potted_wither_rose", "Potted wither rose", "Potted wither rose"),
    ("powder_snow_cauldron", "Powder snow cauldron", "Powder snow cauldron"),
    ("powder_snow", "Powder snow", "Powder snow"),
    ("powered_rail", "Powered rail", "Powered rail"),
    ("prismarine_brick_slab", "Prismarine brick slab", "Prismarine brick slab"),
    ("prismarine_brick_stairs", "Prismarine brick stairs", "Prismarine brick stairs"),
    ("prismarine_bricks", "Prismarine bricks", "Prismarine bricks"),
    ("prismarine_slab", "Prismarine slab", "Prismarine slab"),
    ("prismarine_stairs", "Prismarine stairs", "Prismarine stairs"),
    ("prismarine_wall", "Prismarine wall", "Prismarine wall"),
    ("prismarine", "Prismarine", "Prismarine"),
    ("pumpkin_stem", "Pumpkin stem", "Pumpkin stem"),
    ("pumpkin", "Pumpkin", "Pumpkin"),
    ("purple_banner", "Purple banner", "Purple banner"),
    ("purple_bed", "Purple bed", "Purple bed"),
    ("purple_candle_cake", "Purple candle cake", "Purple candle cake"),
    ("purple_candle", "Purple candle", "Purple candle"),
    ("purple_carpet", "Purple carpet", "Purple carpet"),
    ("purple_concrete_powder", "Purple concrete powder", "Purple concrete powder"),
    ("purple_concrete", "Purple concrete", "Purple concrete"),
    ("purple_glazed_terracotta", "Purple glazed terracotta", "Purple glazed terracotta"),
    ("purple_shulker_box", "Purple shulker box", "Purple shulker box"),
    ("purple_stained_glass_pane", "Purple stained glass pane", "Purple stained glass pane"),
    ("purple_stained_glass", "Purple stained glass", "Purple stained glass"),
    ("purple_terracotta", "Purple terracotta", "Purple terracotta"),
    ("purple_wall_banner", "Purple wall banner", "Purple wall banner"),
    ("purple_wool", "Purple wool", "Purple wool"),
    ("purpur_block", "Purpur block", "Purpur block"),
    ("purpur_pillar", "Purpur pillar", "Purpur pillar"),
    ("purpur_slab", "Purpur slab", "Purpur slab"),
    ("purpur_stairs", "Purpur stairs", "Purpur stairs"),
    ("quartz_block", "Quartz block", "Quartz block"),
    ("quartz_bricks", "Quartz bricks", "Quartz bricks"),
    ("quartz_pillar", "Quartz pillar", "Quartz pillar"),
    ("quartz_slab", "Quartz slab", "Quartz slab"),
    ("quartz_stairs", "Quartz stairs", "Quartz stairs"),
    ("rail", "Rail", "Rail"),
    ("raw_copper_block", "Raw copper block", "Raw copper block"),
    ("raw_gold_block", "Raw gold block", "Raw gold block"),
    ("raw_iron_block", "Raw iron block", "Raw iron block"),
    ("red_banner", "Red banner", "Red banner"),
    ("red_bed", "Red bed", "Red bed"),
    ("red_candle_cake", "Red candle cake", "Red candle cake"),
    ("red_candle", "Red candle", "Red candle"),
    ("red_carpet", "Red carpet", "Red carpet"),
    ("red_concrete_powder", "Red concrete powder", "Red concrete powder"),
    ("red_concrete", "Red concrete", "Red concrete"),
    ("red_glazed_terracotta", "Red glazed terracotta", "Red glazed terracotta"),
    ("red_mushroom_block", "Red mushroom block", "Red mushroom block"),
    ("red_mushroom", "Red mushroom", "Red mushroom"),
    ("red_nether_brick_slab", "Red nether brick slab", "Red nether brick slab"),
    ("red_nether_brick_stairs", "Red nether brick stairs", "Red nether brick stairs"),
    ("red_nether_brick_wall", "Red nether brick wall", "Red nether brick wall"),
    ("red_nether_bricks", "Red nether bricks", "Red nether bricks"),
    ("red_sand", "Red sand", "Red sand"),
    ("red_sandstone_slab", "Red sandstone slab", "Red sandstone slab"),
    ("red_sandstone_stairs", "Red sandstone stairs", "Red sandstone stairs"),
    ("red_sandstone_wall", "Red sandstone wall", "Red sandstone wall"),
    ("red_sandstone", "Red sandstone", "Red sandstone"),
    ("red_shulker_box", "Red shulker box", "Red shulker box"),
    ("red_stained_glass_pane", "Red stained glass pane", "Red stained glass pane"),
    ("red_stained_glass", "Red stained glass", "Red stained glass"),
    ("red_terracotta", "Red terracotta", "Red terracotta"),
    ("red_tulip", "Red tulip", "Red tulip"),
    ("red_wall_banner", "Red wall banner", "Red wall banner"),
    ("red_wool", "Red wool", "Red wool"),
    ("redstone_block", "Redstone block", "Redstone block"),
    ("redstone_lamp", "Redstone lamp", "Redstone lamp"),
    ("redstone_ore", "Redstone ore", "Redstone ore"),
    ("redstone_torch", "Redstone torch", "Redstone torch"),
    ("redstone_wall_torch", "Redstone wall torch", "Redstone wall torch"),
    ("redstone_wire", "Redstone wire", "Redstone wire"),
    ("reinforced_deepslate", "Reinforced deepslate", "Reinforced deepslate"),
    ("repeater", "Repeater", "Repeater"),
    ("repeating_command_block", "Repeating command block", "Repeating command block"),
    ("respawn_anchor", "Respawn anchor", "Respawn anchor"),
    ("rooted_dirt", "Rooted dirt", "Rooted dirt"),
    ("rose_bush", "Rose bush", "Rose bush"),
    ("sand", "Sand", "Sand"),
    ("sandstone_slab", "Sandstone slab", "Sandstone slab"),
    ("sandstone_stairs", "Sandstone stairs", "Sandstone stairs"),
    ("sandstone_wall", "Sandstone wall", "Sandstone wall"),
    ("sandstone", "Sandstone", "Sandstone"),
    ("scaffolding", "Scaffolding", "Scaffolding"),
    ("sculk_catalyst", "Sculk catalyst", "Sculk catalyst"),
    ("sculk_sensor", "Sculk sensor", "Sculk sensor"),
    ("sculk_shrieker", "Sculk shrieker", "Sculk shrieker"),
    ("sculk_vein", "Sculk vein", "Sculk vein"),
    ("sculk", "Sculk", "Sculk"),
    ("sea_lantern", "Sea lantern", "Sea lantern"),
    ("sea_pickle", "Sea pickle", "Sea pickle"),
    ("seagrass", "Seagrass", "Seagrass"),
    ("shroomlight", "Shroomlight", "Shroomlight"),
    ("shulker_box", "Shulker box", "Shulker box"),
    ("skeleton_skull", "Skeleton skull", "Skeleton skull"),
    ("skeleton_wall_skull", "Skeleton wall skull", "Skeleton wall skull"),
    ("slime_block", "Slime block", "Slime block"),
    ("small_amethyst_bud", "Small amethyst bud", "Small amethyst bud"),
    ("small_dripleaf", "Small dripleaf", "Small dripleaf"),
    ("smithing_table", "Smithing table", "Smithing table"),
    ("smoker", "Smoker", "Smoker"),
    ("smooth_basalt", "Smooth basalt", "Smooth basalt"),
    ("smooth_quartz_slab", "Smooth quartz slab", "Smooth quartz slab"),
    ("smooth_quartz_stairs", "Smooth quartz stairs", "Smooth quartz stairs"),
    ("smooth_quartz", "Smooth quartz", "Smooth quartz"),
    ("smooth_red_sandstone_slab", "Smooth red sandstone slab", "Smooth red sandstone slab"),
    ("smooth_red_sandstone_stairs", "Smooth red sandstone stairs", "Smooth red sandstone stairs"),
    ("smooth_red_sandstone", "Smooth red sandstone", "Smooth red sandstone"),
    ("smooth_sandstone_slab", "Smooth sandstone slab", "Smooth sandstone slab"),
    ("smooth_sandstone_stairs", "Smooth sandstone stairs", "Smooth sandstone stairs"),
    ("smooth_sandstone", "Smooth sandstone", "Smooth sandstone"),
    ("smooth_stone_slab", "Smooth stone slab", "Smooth stone slab"),
    ("smooth_stone", "Smooth stone", "Smooth stone"),
    ("sniffer_egg", "Sniffer egg", "Sniffer egg"),
    ("snow_block", "Snow block", "Snow block"),
    ("snow", "Snow", "Snow"),
    ("soul_campfire", "Soul campfire", "Soul campfire"),
    ("soul_fire", "Soul fire", "Soul fire"),
    ("soul_lantern", "Soul lantern", "Soul lantern"),
    ("soul_sand", "Soul sand", "Soul sand"),
    ("soul_soil", "Soul soil", "Soul soil"),
    ("soul_torch", "Soul torch", "Soul torch"),
    ("soul_wall_torch", "Soul wall torch", "Soul wall torch"),
    ("spawner", "Spawner", "Spawner"),
    ("sponge", "Sponge", "Sponge"),
    ("spore_blossom", "Spore blossom", "Spore blossom"),
    ("spruce_button", "Spruce button", "Spruce button"),
    ("spruce_door", "Spruce door", "Spruce door"),
    ("spruce_fence_gate", "Spruce fence gate", "Spruce fence gate"),
    ("spruce_fence", "Spruce fence", "Spruce fence"),
    ("spruce_hanging_sign", "Spruce hanging sign", "Spruce hanging sign"),
    ("spruce_leaves", "Spruce leaves", "Spruce leaves"),
    ("spruce_log", "Spruce log", "Spruce log"),
    ("spruce_planks", "Spruce planks", "Spruce planks"),
    ("spruce_pressure_plate", "Spruce pressure plate", "Spruce pressure plate"),
    ("spruce_sapling", "Spruce sapling", "Spruce sapling"),
    ("spruce_sign", "Spruce sign", "Spruce sign"),
    ("spruce_slab", "Spruce slab", "Spruce slab"),
    ("spruce_stairs", "Spruce stairs", "Spruce stairs"),
    ("spruce_trapdoor", "Spruce trapdoor", "Spruce trapdoor"),
    ("spruce_wall_hanging_sign", "Spruce wall hanging sign", "Spruce wall hanging sign"),
    ("spruce_wall_sign", "Spruce wall sign", "Spruce wall sign"),
    ("spruce_wood", "Spruce wood", "Spruce wood"),
    ("sticky_piston", "Sticky piston", "Sticky piston"),
    ("stone_brick_slab", "Stone brick slab", "Stone brick slab"),
    ("stone_brick_stairs", "Stone brick stairs", "Stone brick stairs"),
    ("stone_brick_wall", "Stone brick wall", "Stone brick wall"),
    ("stone_bricks", "Stone bricks", "Stone bricks"),
    ("stone_button", "Stone button", "Stone button"),
    ("stone_pressure_plate", "Stone pressure plate", "Stone pressure plate"),
    ("stone_slab", "Stone slab", "Stone slab"),
    ("stone_stairs", "Stone stairs", "Stone stairs"),
    ("stone", "Stone", "Stone"),
    ("stonecutter", "Stonecutter", "Stonecutter"),
    ("stripped_acacia_log", "Stripped acacia log", "Stripped acacia log"),
    ("stripped_acacia_wood", "Stripped acacia wood", "Stripped acacia wood"),
    ("stripped_bamboo_block", "Stripped bamboo block", "Stripped bamboo block"),
    ("stripped_birch_log", "Stripped birch log", "Stripped birch log"),
    ("stripped_birch_wood", "Stripped birch wood", "Stripped birch wood"),
    ("stripped_cherry_log", "Stripped cherry log", "Stripped cherry log"),
    ("stripped_cherry_wood", "Stripped cherry wood", "Stripped cherry wood"),
    ("stripped_crimson_hyphae", "Stripped crimson hyphae", "Stripped crimson hyphae"),
    ("stripped_crimson_stem", "Stripped crimson stem", "Stripped crimson stem"),
    ("stripped_dark_oak_log", "Stripped dark oak log", "Stripped dark oak log"),
    ("stripped_dark_oak_wood", "Stripped dark oak wood", "Stripped dark oak wood"),
    ("stripped_jungle_log", "Stripped jungle log", "Stripped jungle log"),
    ("stripped_jungle_wood", "Stripped jungle wood", "Stripped jungle wood"),
    ("stripped_mangrove_log", "Stripped mangrove log", "Stripped mangrove log"),
    ("stripped_mangrove_wood", "Stripped mangrove wood", "Stripped mangrove wood"),
    ("stripped_oak_log", "Stripped oak log", "Stripped oak log"),
    ("stripped_oak_wood", "Stripped oak wood", "Stripped oak wood"),
    ("stripped_spruce_log", "Stripped spruce log", "Stripped spruce log"),
    ("stripped_spruce_wood", "Stripped spruce wood", "Stripped spruce wood"),
    ("stripped_warped_hyphae", "Stripped warped hyphae", "Stripped warped hyphae"),
    ("stripped_warped_stem", "Stripped warped stem", "Stripped warped stem"),
    ("structure_block", "Structure block", "Structure block"),
    ("structure_void", "Structure void", "Structure void"),
    ("sugar_cane", "Sugar cane", "Sugar cane"),
    ("sunflower", "Sunflower", "Sunflower"),
    ("suspicious_gravel", "Suspicious gravel", "Suspicious gravel"),
    ("suspicious_sand", "Suspicious sand", "Suspicious sand"),
    ("sweet_berry_bush", "Sweet berry bush", "Sweet berry bush"),
    ("tall_grass", "Tall grass", "Tall grass"),
    ("tall_seagrass", "Tall seagrass", "Tall seagrass"),
    ("target", "Target", "Target"),
    ("terracotta", "Terracotta", "Terracotta"),
    ("tinted_glass", "Tinted glass", "Tinted glass"),
    ("tnt", "Tnt", "Tnt"),
    ("torch", "Torch", "Torch"),
    ("torchflower_crop", "Torchflower crop", "Torchflower crop"),
    ("torchflower", "Torchflower", "Torchflower"),
    ("trapped_chest", "Trapped chest", "Trapped chest"),
    ("tripwire_hook", "Tripwire hook", "Tripwire hook"),
    ("tripwire", "Tripwire", "Tripwire"),
    ("tube_coral_block", "Tube coral block", "Tube coral block"),
    ("tube_coral_fan", "Tube coral fan", "Tube coral fan"),
    ("tube_coral_wall_fan", "Tube coral wall fan", "Tube coral wall fan"),
    ("tube_coral", "Tube coral", "Tube coral"),
    ("tuff", "Tuff", "Tuff"),
    ("turtle_egg", "Turtle egg", "Turtle egg"),
    ("twisting_vines_plant", "Twisting vines plant", "Twisting vines plant"),
    ("twisting_vines", "Twisting vines", "Twisting vines"),
    ("verdant_froglight", "Verdant froglight", "Verdant froglight"),
    ("vine", "Vine", "Vine"),
    ("void_air", "Void air", "Void air"),
    ("wall_torch", "Wall torch", "Wall torch"),
    ("warped_button", "Warped button", "Warped button"),
    ("warped_door", "Warped door", "Warped door"),
    ("warped_fence_gate", "Warped fence gate", "Warped fence gate"),
    ("warped_fence", "Warped fence", "Warped fence"),
    ("warped_fungus", "Warped fungus", "Warped fungus"),
    ("warped_hanging_sign", "Warped hanging sign", "Warped hanging sign"),
    ("warped_hyphae", "Warped hyphae", "Warped hyphae"),
    ("warped_nylium", "Warped nylium", "Warped nylium"),
    ("warped_planks", "Warped planks", "Warped planks"),
    ("warped_pressure_plate", "Warped pressure plate", "Warped pressure plate"),
    ("warped_roots", "Warped roots", "Warped roots"),
    ("warped_sign", "Warped sign", "Warped sign"),
    ("warped_slab", "Warped slab", "Warped slab"),
    ("warped_stairs", "Warped stairs", "Warped stairs"),
    ("warped_stem", "Warped stem", "Warped stem"),
    ("warped_trapdoor", "Warped trapdoor", "Warped trapdoor"),
    ("warped_wall_hanging_sign", "Warped wall hanging sign", "Warped wall hanging sign"),
    ("warped_wall_sign", "Warped wall sign", "Warped wall sign"),
    ("warped_wart_block", "Warped wart block", "Warped wart block"),
    ("water_cauldron", "Water cauldron", "Water cauldron"),
    ("water", "Water", "Water"),
    ("waxed_copper_block", "Waxed copper block", "Waxed copper block"),
    ("waxed_cut_copper_slab", "Waxed cut copper slab", "Waxed cut copper slab"),
    ("waxed_cut_copper_stairs", "Waxed cut copper stairs", "Waxed cut copper stairs"),
    ("waxed_cut_copper", "Waxed cut copper", "Waxed cut copper"),
    ("waxed_exposed_copper", "Waxed exposed copper", "Waxed exposed copper"),
    ("waxed_exposed_cut_copper_slab", "Waxed exposed cut copper slab", "Waxed exposed cut copper slab"),
    ("waxed_exposed_cut_copper_stairs", "Waxed exposed cut copper stairs", "Waxed exposed cut copper stairs"),
    ("waxed_exposed_cut_copper", "Waxed exposed cut copper", "Waxed exposed cut copper"),
    ("waxed_oxidized_copper", "Waxed oxidized copper", "Waxed oxidized copper"),
    ("waxed_oxidized_cut_copper_slab", "Waxed oxidized cut copper slab", "Waxed oxidized cut copper slab"),
    ("waxed_oxidized_cut_copper_stairs", "Waxed oxidized cut copper stairs", "Waxed oxidized cut copper stairs"),
    ("waxed_oxidized_cut_copper", "Waxed oxidized cut copper", "Waxed oxidized cut copper"),
    ("waxed_weathered_copper", "Waxed weathered copper", "Waxed weathered copper"),
    ("waxed_weathered_cut_copper_slab", "Waxed weathered cut copper slab", "Waxed weathered cut copper slab"),
    ("waxed_weathered_cut_copper_stairs", "Waxed weathered cut copper stairs", "Waxed weathered cut copper stairs"),
    ("waxed_weathered_cut_copper", "Waxed weathered cut copper", "Waxed weathered cut copper"),
    ("weathered_copper", "Weathered copper", "Weathered copper"),
    ("weathered_cut_copper_slab", "Weathered cut copper slab", "Weathered cut copper slab"),
    ("weathered_cut_copper_stairs", "Weathered cut copper stairs", "Weathered cut copper stairs"),
    ("weathered_cut_copper", "Weathered cut copper", "Weathered cut copper"),
    ("weeping_vines_plant", "Weeping vines plant", "Weeping vines plant"),
    ("weeping_vines", "Weeping vines", "Weeping vines"),
    ("wet_sponge", "Wet sponge", "Wet sponge"),
    ("wheat", "Wheat", "Wheat"),
    ("white_banner", "White banner", "White banner"),
    ("white_bed", "White bed", "White bed"),
    ("white_candle_cake", "White candle cake", "White candle cake"),
    ("white_candle", "White candle", "White candle"),
    ("white_carpet", "White carpet", "White carpet"),
    ("white_concrete_powder", "White concrete powder", "White concrete powder"),
    ("white_concrete", "White concrete", "White concrete"),
    ("white_glazed_terracotta", "White glazed terracotta", "White glazed terracotta"),
    ("white_shulker_box", "White shulker box", "White shulker box"),
    ("white_stained_glass_pane", "White stained glass pane", "White stained glass pane"),
    ("white_stained_glass", "White stained glass", "White stained glass"),
    ("white_terracotta", "White terracotta", "White terracotta"),
    ("white_tulip", "White tulip", "White tulip"),
    ("white_wall_banner", "White wall banner", "White wall banner"),
    ("white_wool", "White wool", "White wool"),
    ("wither_rose", "Wither rose", "Wither rose"),
    ("wither_skeleton_skull", "Wither skeleton skull", "Wither skeleton skull"),
    ("wither_skeleton_wall_skull", "Wither skeleton wall skull", "Wither skeleton wall skull"),
    ("yellow_banner", "Yellow banner", "Yellow banner"),
    ("yellow_bed", "Yellow bed", "Yellow bed"),
    ("yellow_candle_cake", "Yellow candle cake", "Yellow candle cake"),
    ("yellow_candle", "Yellow candle", "Yellow candle"),
    ("yellow_carpet", "Yellow carpet", "Yellow carpet"),
    ("yellow_concrete_powder", "Yellow concrete powder", "Yellow concrete powder"),
    ("yellow_concrete", "Yellow concrete", "Yellow concrete"),
    ("yellow_glazed_terracotta", "Yellow glazed terracotta", "Yellow glazed terracotta"),
    ("yellow_shulker_box", "Yellow shulker box", "Yellow shulker box"),
    ("yellow_stained_glass_pane", "Yellow stained glass pane", "Yellow stained glass pane"),
    ("yellow_stained_glass", "Yellow stained glass", "Yellow stained glass"),
    ("yellow_terracotta", "Yellow terracotta", "Yellow terracotta"),
    ("yellow_wall_banner", "Yellow wall banner", "Yellow wall banner"),
    ("yellow_wool", "Yellow wool", "Yellow wool"),
    ("zombie_head", "Zombie head", "Zombie head"),
    ("zombie_wall_head", "Zombie wall head", "Zombie wall head"),
]